export enum InterestEnum {
  BUSINESS_ACTIVITY = 'BUSINESS_ACTIVITY',
  MOUNTAINEERING = 'MOUNTAINEERING',
  LOCAL_CULTURE = 'LOCAL_CULTURE',
  EASY_WALKS = 'EASY_WALKS',
  EXTREME_ADVENTURE = 'EXTREME_ADVENTURE',
  REGIONAL_FOOD = 'REGIONAL_FOOD',
  BIKE_ROUTES = 'BIKE_ROUTES',
}
