export enum NotificationTypesEnum {
  NEW_REVIEW_COMPLETED = 'new_review_completed',
  USER_INVITATION_SENT = 'invitation_sent',
  USER_INVITATION_ACCEPTED = 'invitation_accepted',
  NEW_BUSINESS_REQUEST = 'new_business_request',
  CART_STATUS_CHANGED = 'cart_status_changed',
  CART_CREATED = 'cart_created',
  REVIEW_REWARD = 'review_reward',
  CONFIRMED_CREDIT_PURCHASE = 'confirmed_credit_purchase',
  CREDIT_PURCHASE_IN_REVIEW = 'credit_purchase_in_review',
  CREDIT_PURCHASE_CANCELLED = 'credit_purchase_cancelled',
  CREDIT_PURCHASE_REQUESTED = 'credit_purchase_requested',
  CONFIRMED_SUBSCRIPTION_PURCHASE = 'confirmed_subscription_purchase',
  SUBSCRIPTION_PURCHASE_IN_REVIEW = 'subscription_purchase_in_review',
  SUBSCRIPTION_PURCHASE_CANCELLED = 'subscription_purchase_cancelled',
  SUBSCRIPTION_PURCHASE_REQUESTED = 'subscription_purchase_requested',
  SUBSCRIPTION_EXPIRING = 'subscription_expiring',
}
