export enum ProfessionalViewEnum {
  LOCAL_GUIDE = 'LOCAL_GUIDE',
  SCIENTIST = 'SCIENTIST',
  FOOD_CRITIC = 'FOOD_CRITIC',
  HISTORIAN = 'HISTORIAN',
  ENVIRONMENTALIST = 'ENVIRONMENTALIST',
  RELIGIOUS_SCHOLAR = 'RELIGIOUS_SCHOLAR',
  TRAVEL_BLOGGER = 'TRAVEL_BLOGGER',
}
